### PR TITLE
Fixes for PRG injection and simple T64 file support.

### PR DESCRIPTION
**Pull request by nanner55**
PRG RAM injection needs to init several pointer location in the 0-FF range in memory.  This is normally done during a LOAD BASIC command inside the interpreter, but injection doesn't have the ability to call it.  Without init of memory, BASIC execution can have errors.  E.g. the game $1,000,000 first allocates a 17 element array on the heap, DIM Q(16), which results in the code segment being overwritten with 0s which causes the interpreter to exit after hitting a 0 pointer.  The change inits several pointers after the download is complete and before the RUN command.

This commit also adds simple support for the T64 file format.  It attempts to load the first record at the location specified in the T64 header by extending the PRG RAM injection code.

### CODE REVIEW

**Comment by sorgelig** [comment]
T64 support is like pandora's box.. There will be a lot of reports that someone's lovely T64 doesn't work.
T64 is like disk image with many files inside. So only few single file apps/games will work.

**Comment by sorgelig** [comment]
It could me more wise to include T64->D64 auto converter on HPS side, so T64 will be mounted as disk.

**Comment by nanner55** [comment]
I agree that the T64 format is overly general making the fields in the header very error prone.  I can make a separate pull request without T64 support or, if you want, you can remove T64 in the confstr.  It's a tradeoff of supporting the most common case (single record) and dealing with reports vs not supporting it which makes the user deal with the conversion to supported formats.

Even a more general solution is going to have the same problems emulators have with parsing it.  PRG should probably be mounted as a disk, too, so it can be LOADed.

**Comment by sorgelig** [comment]
i'm trying to be a reasonable. There is no point to mount prg as a disk. It's more reasonable to inject it as it's done. Thanks for fixing the injector!

**Comment by nanner55** [comment]
I'll take a look at mounting the T64 as a disk with multiple files.  That's a better way to do it which will work with more T64 files.

**Pull request merged**
