### PR TITLE
add japanese kernal and character rom

### PR DESCRIPTION
**Pull request by makigumo**
This adds  the Japanese kernal and character rom to the Kernal menu.
See also http://www.zimmers.net/cbmpics/c64js.html

20210205_214500-screen

### CODE REVIEW

**Comment by sorgelig** [comment]
There an option to use a loadable rom. So you can build whatever rom set you like without modifying the core.

**Comment by makigumo** [comment]
Yes, but you cant load a different character rom, or can you? Also this is not an unofficial or third-party ROM like JiffyDOS. This is an official ROM of the C64 released by Commodore in the Japanese market, essentially like for the C64GS.

**Comment by sorgelig** [comment]
PR is not well formed it includes tons of changes not related to subject. Probably related to line ending type. You need to set the option in your local git to ignore line ending when you push the commit, so it won't commit lines auto-converted by your text editor.

**Comment by makigumo** [comment]
Thanks for the hint, I tried to clean up the changes as best as I could.
In the long run it may be advisable to unify the line endings in all files. Currently there is a mixture of Windows (CRLF) and UNIX (LF) line endings in those files.

**Comment by sorgelig** [comment]
some devs use linux, some use windows. It's impossible to unify

**Comment by sorgelig** [comment]
i've added your changes manually.

**Comment by makigumo** [comment]
Thank you!

**Pull request closed without merging**
