### PR TITLE
Resolve most connectivity warnings.

### PR DESCRIPTION
**Pull request by vpelletier**
Beyond what is listed in the commit message, some attention points:
- I did only very minimal tests beyond building. Most of the changes should be trivial enough to be obviously-correct, I believe.
- in OPL3, `period_80us` is also used in another instance, and in that case it is padded the other way:
`{period_80us, 2'b00}`. For the sake of not having to think (as I am not familiar with the OPL3), I padded the MSb with zeros, as I believe this is what the sythetiser does.
- I am not completely sure of `tap_last_addr <= tape_download ? ioctl_addr[24:0]+2'd2 : 25'd0;`, and have no tape image to test this against.

### CODE REVIEW

**Comment by sorgelig** [comment]
I don't see the point of such "corrections". It's perfectly handled by synthesizer which even doesn't produce the warnings. It's just matter of style.
For example i hate to write 1'b0 where simple 0 is fine. It improves the readability.

**Comment by vpelletier** [comment]
Just to be sure I do not miss anything (still getting used to the languages, the tools, and still making stupid combinatorial mistakes), in Quartus 19.1 there are warnings issued, just not in the general log: there is a single line with a warning count and a reference to "connectivity checks" section of the compilation report. This commit brings the number of warnings from a few tens to 9.

I do agree that all these bit-widths and explicit no-connections make the code less readable, anyway.

About the OPL3 thing, I think the point still holds that existing code may have a bug (same signal used in 2 instances with a 2-bits shift difference looks wrong).

**Comment by sorgelig** [comment]
I will check OPL3 code.
Official Quartus version for MiSTer is 17.0.xx 
There is no point to use higher versions - they give nothing new, but mess the configs. So if you plan to submit PRs then it's better to use the same version.

**Comment by sorgelig** [comment]
Timer code In OPL3 is correct. Second timer is 4 times slower than first one. That's why it's period is 4 times larger.

**Pull request closed without merging**
